WORKDIR /home/app

VOLUME /var/log/


#RUN  mkdir -p  /var/www/ ;\
#	 ln -s /home/app /var/www/html ;\
#	 ls -la  /var/www/


ADD home/start.sh /home/engines/scripts/startup/start.sh

RUN /home/engines/scripts/build/post_build_clean.sh
	





