requires 'lib',
         'recovery',
         'asserting',
         'models',
         'spaces',
         'classifying',
         'streaming',
         'commands',
         'universes',
         'controllers',
         'git',
         'interpolating'
