#!/bin/sh -e

# If this isn't included build will hang forever if dpkg asks any questions.
export DEBIAN_FRONTEND=noninteractive

[ -n "$BLUEPRINT_PACKAGE_REMOVES" ] && apt-get purge -y --autoremove $BLUEPRINT_PACKAGE_REMOVES
