require_level 'spaces/engines/transforming'
require_level 'spaces/engines/transforming/divisions'
require_level 'spaces/engines/transforming/divisions/bindings'
require_all   'spaces/engines/transforming/emissions'

require_all   'spaces/engines/arenas'
require_all   'spaces/engines/packing'
require_all   'spaces/engines/publishing'
require_all   'spaces/engines/blueprinting'
require_all   'spaces/engines/locating'
require_all   'spaces/engines/settling'
require_all   'spaces/engines/installing'
require_all   'spaces/engines/resolving'
require_all   'spaces/engines/provisioning'

require_all   'spaces/engines/provider_aspects'
