USER 0

RUN	chmod -R g+r /home/app;\
 	for dir in  `find /home/app -type d | sed "/ /s/+_+//g"` ;\
	  do\
		if test `echo $dir |grep _+_ |wc -l ` -lt 1 ;\
			then \
				chmod g+x  $dir ;\
		fi;\
	  done;\
  /build_scripts/configure_apache.sh
  
USER $ContUser
