#!/bin/sh -e

# If this isn't included build will hang forever if dpkg asks any questions.
export DEBIAN_FRONTEND=noninteractive

[ -n "$ENGINES_PACKAGES" ] && apt-get install -y --no-install-recommends $ENGINES_PACKAGES
