ENV ContUser www-data

WORKDIR /home/app

VOLUME /var/log/

RUN ln -s /home/app /var/www &&\
    usermod -G data-user -a www-data &&\
    mkdir -p /home/app/tmp &&\
    chmod u+w /home/app/tmp

ADD home/start.sh /home/spaces/scripts/startup/start.sh


