#!/bin/sh -e

heading() {
  echo "==> $1 <=="
}

heading "Removing all existing sources.list{,.d} files"
rm -f /etc/apt/sources.list
rm -f /etc/apt/sources.list.d/*.list

suite=${suite:=beowulf}
src=/etc/apt/sources.list.d/$suite.list

heading "Setting up sources.list for: $suite"

uri=http://aptcacher.int.filterfish.org:3142/auto.mirror.devuan.org/merged
component=main
apt_conf=/etc/apt/apt.conf.d/01-minimal-install

suites="$suite $suite-updates $suite-backports $suite-security"

# Install a sensible sources.list
echo "# Set up by packer - probably best not to touch it.\n" > $src
for s in $suites; do
  echo "deb $uri $s $component" >> $src
done

# Ensure we only install the required packages
# This came from: https://git.devuan.org/dev1fanboy/Upgrade-Install-Devuan/wikis/Upgrade-to-Devuan-and-minimalism

heading "Setting up apt"
cat > $apt_conf << EOF
APT::Install-Suggests "false";
APT::Install-Recommends "false";
APT::AutoRemove::SuggestsImportant "false";
APT::AutoRemove::RecommendsImportant "false";

DPkg::options {
  "--force-confold";
}
EOF

# If this isn't included build will hang forever if dpkg asks any questions.
export DEBIAN_FRONTEND=noninteractive

heading "Upgrading the system"
apt-get update
apt-get dist-upgrade -yy
