#!/bin/sh -e
# From https://github.com/box-cutter/debian-vm/blob/master/script/cleanup.sh
# Then from https://github.com/jakobadam/packer-qemu-templates

heading() {
  echo "==> $1 <=="
}

heading "Removing leftover dhcp leases"
if [ -d "/var/lib/dhcp" ]; then
    find /var/lib/dhcp -type f -delete
fi

heading "Removing stale /tmp files"
rm -rf /tmp/*

heading "Cleaning up APT"
apt-get -y autoremove --purge
apt-get -y clean
apt-get -y autoclean

heading "Really cleaning up APT"
find /var/lib/apt -type f -delete
find /var/cache/apt -type f -delete

heading "Removing unnecessary man files"
find /usr/share/man -maxdepth 1 \( -name '??' -o -name '??[._]*' \) -print | xargs -r rm -r

heading "Removing shell history files"
rm -f /root/.bash_history
rm -f /root/.histfile

heading "Removing log files"
find /var/log -type f | while read -r f; do :> "$f"; done;

heading "Removing dist/auto-upgrade files"
find / -xdev \( -name \*.dpkg-dist -o -name \*.ucf-dist -o -name \*.dpkg-old -o -name \*.dpkg-new -o -name \*.dpkg-tmp \) -delete

heading "Remove the packer files directory"
rm -rf /files
