#!/bin/sh -e

# If this isn't included build will hang forever if dpkg asks any questions.
export DEBIAN_FRONTEND=noninteractive

[ -n "$BLUEPRINT_PACKAGE_ADDS" ] && apt-get install -y --no-install-recommends $BLUEPRINT_PACKAGE_ADDS
