#!/bin/sh -e

# If this isn't included build will hang forever if dpkg asks any questions.
export DEBIAN_FRONTEND=noninteractive
if test -z $SYSTEM_PACKAGE_REMOVES
	then 
		SYSTEM_PACKAGE_REMOVES="$*"
fi		

if test -n "$SYSTEM_PACKAGE_REMOVES"
	then
		apt-get purge -y --autoremove $SYSTEM_PACKAGE_REMOVES
fi
